import { MaterialDataInput } from "./materialData";
import { MaterialRegistry } from "./materialRegistry";

/**
 * DEFAULT_MATERIALS — a small, illustrative starter catalog.
 *
 * This is DATA, not algorithm: the transformation graph, damage rules, and
 * structural math never hardcode any of these ids. Team 02 (and later
 * content authors) are expected to register their own materials via
 * `MaterialRegistry.register` — this catalog exists only so Team 03's own
 * tests, transformation examples, and object generators have something
 * concrete to run against without waiting on Team 02.
 */
export const DEFAULT_MATERIALS: readonly MaterialDataInput[] = [
  {
    id: "oak_wood",
    name: "Oak Wood",
    category: "wood",
    density: 700,
    hardness: 0.45,
    strength: 0.5,
    toughness: 0.55,
    elasticity: 0.35,
    flammability: 0.7,
    thermalConductivity: 0.15,
    thermalCapacity: 0.4,
    waterResistance: 0.3,
    corrosionResistance: 1,
    decayRate: 0.01,
    friction: 0.5,
    colorDescriptor: "warm brown",
    state: "solid",
    temperatureRange: { minC: -50, maxC: 300 },
  },
  {
    id: "plank",
    name: "Wooden Plank",
    category: "wood",
    density: 650,
    hardness: 0.4,
    strength: 0.45,
    toughness: 0.4,
    elasticity: 0.3,
    flammability: 0.75,
    thermalConductivity: 0.15,
    thermalCapacity: 0.38,
    waterResistance: 0.25,
    corrosionResistance: 1,
    decayRate: 0.015,
    friction: 0.45,
    colorDescriptor: "pale brown",
    state: "solid",
    temperatureRange: { minC: -50, maxC: 300 },
  },
  {
    id: "charcoal",
    name: "Charcoal",
    category: "organic",
    density: 210,
    hardness: 0.2,
    strength: 0.15,
    toughness: 0.1,
    elasticity: 0.05,
    flammability: 0.95,
    thermalConductivity: 0.2,
    thermalCapacity: 0.5,
    waterResistance: 0.2,
    corrosionResistance: 1,
    decayRate: 0.005,
    friction: 0.4,
    colorDescriptor: "matte black",
    state: "solid",
    temperatureRange: { minC: -50, maxC: 900 },
  },
  {
    id: "granite",
    name: "Granite",
    category: "stone",
    density: 2700,
    hardness: 0.9,
    strength: 0.85,
    toughness: 0.7,
    elasticity: 0.05,
    flammability: 0,
    thermalConductivity: 0.3,
    thermalCapacity: 0.25,
    waterResistance: 0.9,
    corrosionResistance: 0.85,
    decayRate: 0.0005,
    friction: 0.7,
    colorDescriptor: "speckled grey",
    state: "solid",
    temperatureRange: { minC: -200, maxC: 1200 },
  },
  {
    id: "cut_stone",
    name: "Cut Stone Block",
    category: "stone",
    density: 2650,
    hardness: 0.88,
    strength: 0.82,
    toughness: 0.65,
    elasticity: 0.04,
    flammability: 0,
    thermalConductivity: 0.3,
    thermalCapacity: 0.25,
    waterResistance: 0.88,
    corrosionResistance: 0.85,
    decayRate: 0.0006,
    friction: 0.65,
    colorDescriptor: "even grey",
    state: "solid",
    temperatureRange: { minC: -200, maxC: 1200 },
  },
  {
    id: "iron_ore",
    name: "Iron Ore",
    category: "stone",
    density: 3800,
    hardness: 0.6,
    strength: 0.4,
    toughness: 0.3,
    elasticity: 0.02,
    flammability: 0,
    thermalConductivity: 0.4,
    thermalCapacity: 0.2,
    waterResistance: 0.8,
    corrosionResistance: 0.5,
    decayRate: 0.0003,
    friction: 0.6,
    colorDescriptor: "rust-red flecked stone",
    state: "solid",
    temperatureRange: { minC: -200, maxC: 1500 },
  },
  {
    id: "iron",
    name: "Iron",
    category: "metal",
    density: 7870,
    hardness: 0.7,
    strength: 0.75,
    toughness: 0.6,
    elasticity: 0.55,
    flammability: 0,
    thermalConductivity: 0.75,
    thermalCapacity: 0.3,
    waterResistance: 0.4,
    corrosionResistance: 0.3,
    decayRate: 0.003,
    friction: 0.35,
    colorDescriptor: "dull silver-grey",
    state: "solid",
    temperatureRange: { minC: -200, maxC: 1538 },
  },
  {
    id: "clay",
    name: "Wet Clay",
    category: "clay",
    density: 1900,
    hardness: 0.1,
    strength: 0.1,
    toughness: 0.2,
    elasticity: 0.6,
    flammability: 0,
    thermalConductivity: 0.2,
    thermalCapacity: 0.3,
    waterResistance: 0.1,
    corrosionResistance: 1,
    decayRate: 0.002,
    friction: 0.8,
    colorDescriptor: "damp ochre",
    state: "solid",
    temperatureRange: { minC: -30, maxC: 100 },
  },
  {
    id: "brick",
    name: "Fired Brick",
    category: "composite",
    density: 1900,
    hardness: 0.65,
    strength: 0.6,
    toughness: 0.45,
    elasticity: 0.03,
    flammability: 0,
    thermalConductivity: 0.25,
    thermalCapacity: 0.28,
    waterResistance: 0.75,
    corrosionResistance: 0.9,
    decayRate: 0.0008,
    friction: 0.7,
    colorDescriptor: "terracotta red",
    state: "solid",
    temperatureRange: { minC: -200, maxC: 1000 },
  },
  {
    id: "sand",
    name: "Sand",
    category: "sand",
    density: 1600,
    hardness: 0.15,
    strength: 0.05,
    toughness: 0.05,
    elasticity: 0.01,
    flammability: 0,
    thermalConductivity: 0.1,
    thermalCapacity: 0.2,
    waterResistance: 0.5,
    corrosionResistance: 1,
    decayRate: 0,
    friction: 0.9,
    colorDescriptor: "pale tan",
    state: "powder",
    temperatureRange: { minC: -200, maxC: 1600 },
  },
  {
    id: "glass",
    name: "Glass",
    category: "glass",
    density: 2500,
    hardness: 0.55,
    strength: 0.2,
    toughness: 0.05,
    elasticity: 0.02,
    flammability: 0,
    thermalConductivity: 0.2,
    thermalCapacity: 0.2,
    waterResistance: 1,
    corrosionResistance: 1,
    decayRate: 0,
    friction: 0.2,
    colorDescriptor: "clear",
    state: "solid",
    temperatureRange: { minC: -200, maxC: 550 },
  },
  {
    id: "plant_fiber",
    name: "Plant Fiber",
    category: "organic",
    density: 400,
    hardness: 0.1,
    strength: 0.2,
    toughness: 0.25,
    elasticity: 0.4,
    flammability: 0.8,
    thermalConductivity: 0.1,
    thermalCapacity: 0.35,
    waterResistance: 0.2,
    corrosionResistance: 1,
    decayRate: 0.03,
    friction: 0.6,
    colorDescriptor: "dry straw yellow",
    state: "solid",
    temperatureRange: { minC: -30, maxC: 200 },
  },
  {
    id: "rope",
    name: "Rope",
    category: "fabric",
    density: 500,
    hardness: 0.1,
    strength: 0.35,
    toughness: 0.4,
    elasticity: 0.45,
    flammability: 0.7,
    thermalConductivity: 0.1,
    thermalCapacity: 0.35,
    waterResistance: 0.25,
    corrosionResistance: 1,
    decayRate: 0.02,
    friction: 0.65,
    colorDescriptor: "twisted fiber tan",
    state: "solid",
    temperatureRange: { minC: -30, maxC: 200 },
  },
  {
    id: "water",
    name: "Water",
    category: "water",
    density: 1000,
    hardness: 0,
    strength: 0,
    toughness: 0,
    elasticity: 0,
    flammability: 0,
    thermalConductivity: 0.5,
    thermalCapacity: 1,
    waterResistance: 1,
    corrosionResistance: 0,
    decayRate: 0,
    friction: 0.05,
    colorDescriptor: "clear blue",
    state: "liquid",
    temperatureRange: { minC: 0, maxC: 100 },
  },
  {
    id: "ice",
    name: "Ice",
    category: "ice",
    density: 917,
    hardness: 0.3,
    strength: 0.15,
    toughness: 0.1,
    elasticity: 0.1,
    flammability: 0,
    thermalConductivity: 0.4,
    thermalCapacity: 0.5,
    waterResistance: 0.9,
    corrosionResistance: 1,
    decayRate: 0,
    friction: 0.05,
    colorDescriptor: "pale translucent blue",
    state: "solid",
    temperatureRange: { minC: -200, maxC: 0 },
  },
];

/** Builds a fresh MaterialRegistry pre-populated with the default catalog. */
export function createDefaultMaterialRegistry(): MaterialRegistry {
  return MaterialRegistry.create(DEFAULT_MATERIALS);
}
